<template>
	<div class="guess-pokemon">
		<div class="guess-pokemon__image">
			<img :class="{ show: isActive }" :src="pokemonPicture" :alt="altText" />
		</div>

		<h1 class="pokemon-font">{{ pokemonOutput }}</h1>

		<!-- Creates one button containing a pokemon name for each pokemon name in buttonGuesses -->
		<!-- @click.once=onClickCheck(index) click.once is used here to stop the setTimeout method in the onClickCheck method from looping if the success button is clicked several times. -->
		<button
			@click.once="onClickCheck(index)"
			ref="answerButtons"
			class="guess-pokemon__buttons"
			v-for="(guesses, index) in this.buttonGuesses"
			:key="guesses"
		>
			<!-- Checks whether the index matches correctAnswer which is a randomly computed value if it is, insert correctPokemon (Did this to get the answer at a random index)  -->
			<div v-if="index === correctAnswer">
				{{ correctPokemon }}
			</div>
			<div v-else>{{ guesses }}</div>
		</button>
	</div>
</template>

<script>
export default {
	data() {
		return {
			pokemonOutput: "who's that Pokemon?",
			correctPokemon: '',
			buttonGuesses: [],
			pokemonPicture: '',
			correctAnswer: 0,
			isActive: false,
			correctButtonPressed: false,
			altText: 'Image of a pokemon',
			randomIdsUsed: [], //Array used to keep track of what pokemons has been fetched
			allPokemon: []
		};
	},

	async created() {
		if(this.allPokemon.lenght > 0){
			this.fetchPokemon();
		}
		
		//Executes runApp method which starts the app.
		this.runApp();
	},

	methods: {
		async fetchPokemon() {
			const url = 'https://pokeapi.co/api/v2/pokemon';
			const response = await fetch(url);
			const { results } = await response.json();
			this.allPokemon = results;
		},

		//Method used to start the app.
		runApp() {
			this.resetAppData();

			//Gets a random pokemon from the pokeapi using a random number generated by randomId();
			this.getCorrectPokemon();

			//Inserts random pokemons into the buttonGuesses array in data().
			this.insertRandomPokemons();
		},

		//Method used to reset all the data properties used in the app to their default starting values. We also use it when starting the app.
		resetAppData() {
			//Reset the correctButtonPressed data which is used to stop users from pressing buttons once the correct button is pressed.
			this.correctButtonPressed = false;

			//Resets random ids used to be empty.
			this.randomIdsUsed = [];

			//The property used to output the text in the app.
			this.pokemonOutput = "Who's that Pokemon?";

			//Uses the randomButtonNumber method to set the correctAnswer to be a number between 0 and 3.
			this.correctAnswer = this.randomButtonNumber();
			this.buttonGuesses = [];

			//Changes the isActive property to true, which enables the .show class that makes the image dark.
			this.isActive = false;
		},

		getJSON(url, errorMsg) {
			fetch(url).then((response) => {
				if (!response.ok) {
					throw new Error(`${errorMsg} ${response.status}`);
				}
				return response.json();
			});
		},

		//Gets the pokemon used as the correct answer, and sets the image and name of that pokemon.
		getCorrectPokemon() {
			//Generates an id used to get a random pokemon.
			const pokemonId = this.randomId();

			//Builds a promise from the pokeapi and returns it for us to consume.

			//Handle the promise by using .then and since .then returns another promise we use another .then to handle that promise and get the data.

			fetch(`https://pokeapi.co/api/v2/pokemon/${pokemonId}`)
				.then((response) => {
					if (!response.ok) {
						throw new Error(`Pokemon not found ${response.status}`);
					}
					return response.json();
				})
				.then((data) => {
					this.pokemonPicture = data.sprites.front_default;
					this.correctPokemon = this.capitalizeString(data.name);
				})
				.catch((error) => {
					console.error(`${error}`);
					this.pokemonPicture = '/src/assets/images/25.png';
					this.correctPokemon = 'Pikachu';
				});

			this.randomIdsUsed.push(pokemonId);
		},

		//Gets a random pokemon from the pokeApi and pushes it to the buttonGuesses array.
		getRandomPokemonName() {
			const randomId = this.randomId();

			//This conditional checks if the randomId is already existing in the array, and if it is, rerun this function and generate a new randomId. We do this to guarantee that we only send a request to the pokeAPI for NEW pokemons, and not duplicates.
			if (this.randomIdsUsed.includes(randomId)) {
				this.getRandomPokemonName();
			} else {
				fetch(`https://pokeapi.co/api/v2/pokemon/${randomId}`)
					.then((response) => {
						if (!response.ok) {
							throw new Error(`Pokemon not found ${response.status}`);
						}
						return response.json();
					})
					.then((data) => {
						this.buttonGuesses.push(this.capitalizeString(data.name));
					})
					.catch((error) => {
						console.error(
							'ERROR couldnt get a random pokemon, request failed ' + error
						);

						this.buttonGuesses.push('Unknown');
					});

				//Pushes the id used to the randomIdsUsed array, so we can keep track of all the ids used.
				this.randomIdsUsed.push(randomId);
			}
		},

		//Gets random pokemons from the pokeapi, by using the getRandomPokemonName function.
		insertRandomPokemons() {
			//Runs the getRandomPokemonName function 4 times.
			for (let i = 0; 4 > i; i++) {
				this.getRandomPokemonName();
			}
		},

		//Generates a random number used for pokemonId, the number is used in the pokeapi http link to get a random pokemon.
		randomId() {
			let randomId = Math.floor(Math.random() * 151) + 1;

			//Adding +1 because the pokeApi doesn't have a data at the id 0, so we need to make sure that Math.floor will be 1.
			return randomId;
		},

		//Checks if the index of the button clicked matches the number in correctAnswer, correctAnswer is generated by randomButtonNumber() in resetAppData()
		onClickCheck(buttonElementIndex) {
			if (this.correctButtonPressed) return;

			if (buttonElementIndex === this.correctAnswer) {
				this.correctButtonPressed = true;
				//Changes isActive property which is used to determine if the image should be black or not.
				this.isActive = true;

				//Uses refs to add the correct class styling when the correct button is clicked by using the index we get from the v-for on the elements this click function is attached to.
				this.$refs.answerButtons[buttonElementIndex].classList.add(
					'guess-pokemon__button--correct'
				);
				this.pokemonOutput = `It's ${this.correctPokemon}!`;

				//Starts a setTimeout on correct answer to start the app again.
				setTimeout(() => this.runApp(), 2000);
			} else {
				//Uses refs to check if the button clicked is incorrect, and applies said class to the clicked element.
				this.$refs.answerButtons[buttonElementIndex].classList.add(
					'guess-pokemon__buttons--incorrect'
				);
			}
		},

		//Capitalizes the first character of a string. (Used to capitalize the names from the pokeapi, since they were are all lowercase by default)
		capitalizeString(string) {
			return string.charAt(0).toUpperCase() + string.slice(1);
		},

		//Generates a random number between 0 and 3 which is used to determine which button to insert the correct pokemon name.
		randomButtonNumber() {
			return Math.floor(Math.random() * 4);
		},
	},
};
</script>

<style>
.pokemon-font {
	color: #ffcb05;
	-webkit-text-stroke-width: 0.06em;
	-webkit-text-stroke-color: #385aaa;
	letter-spacing: 4px;
	font-size: 20px;
	text-align: center;
	font-family: 'pokemon-font';
	margin-bottom: 1rem;
}

.guess-pokemon {
	margin: 1rem;
}

.guess-pokemon__image {
	background-color: #62ddd5;
	border-radius: 50%;
	border: 4px solid #ffcb05;
	width: 200px;
	margin: 30px auto;
	height: auto;
}

.guess-pokemon__image img {
	filter: brightness(0%);
}

@keyframes example {
	from {
		filter: brightness(10%);
	}
	to {
		filter: brightness(100%);
	}
}
.show {
	filter: brightness(100%);
	animation-name: example;
	animation-duration: 2s;
}

.guess-pokemon__buttons {
	background-color: #ffcb05;
	display: block;
	color: rgb(54, 54, 54);
	width: 100%;
	max-width: 450px;
	padding: 0.8em;
	margin: 0.6rem auto;
	border-radius: 4px;
	border: solid 2px rgba(0, 10, 66, 0.61);
	font-family: 'Press Start 2P', cursive;
	font-size: 14px;
}

.guess-pokemon__button--correct {
	background-color: rgb(0, 180, 0);
}

.guess-pokemon__buttons--incorrect {
	background-color: rgb(207, 41, 41);
	text-decoration: line-through;
}
</style>
